server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        # Because we use the Router in react, we need to have different attempts at routing to a location.
        try_files $uri $uri/ /index.html;
    }
}
